### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Motorloid01** [weeryan17/Discord-Groups#11]
[01:35:48 INFO]: 01:35:48.930
[01:35:48 INFO]: : [
[01:35:48 INFO]: INFO
[01:35:48 INFO]: ][
[01:35:48 INFO]: HttpClient@1356741957-173
[01:35:48 INFO]: ][
[01:35:48 INFO]: sx.blah.discord.Discord4J
[01:35:48 INFO]: ] -
[01:35:48 INFO]: Connected to Discord Gateway v5. Receiving 1 guilds.
[01:35:48 INFO]:

[01:35:49 INFO]: [DiscordGroups] bot ready
[01:35:49 INFO]: [DiscordGroups] Current channel checking: general
[01:35:49 WARN]: sx.blah.discord.util.MissingPermissionsException: Missing permissions: MANAGE_ROLES!
[01:35:49 WARN]:        at sx.blah.discord.api.internal.DiscordUtils.checkPermissions(DiscordUtils.java:718)
[01:35:49 WARN]:        at sx.blah.discord.api.internal.DiscordUtils.checkPermissions(DiscordUtils.java:638)
[01:35:49 WARN]:        at sx.blah.discord.api.internal.DiscordUtils.checkPermissions(DiscordUtils.java:696)
[01:35:49 WARN]:        at sx.blah.discord.handle.impl.obj.Guild.createRole(Guild.java:361)
[01:35:49 WARN]:        at com.weeryan17.discord.Updater.updateRoles(Updater.java:55)
[01:35:49 WARN]:        at com.weeryan17.discord.DiscordEventHandler.onReadyEvent(DiscordEventHandler.java:43)
[01:35:49 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[01:35:49 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[01:35:49 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[01:35:49 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[01:35:49 WARN]:        at sx.blah.discord.api.events.EventDispatcher.lambda$null$12(EventDispatcher.java:343)
[01:35:49 WARN]:        at java.util.concurrent.CopyOnWriteArrayList.forEach(Unknown Source)
[01:35:49 WARN]:        at sx.blah.discord.api.events.EventDispatcher.lambda$null$13(EventDispatcher.java:341)
[01:35:49 WARN]:        at java.util.concurrent.ConcurrentHashMap.forEach(Unknown Source)
[01:35:49 WARN]:        at sx.blah.discord.api.events.EventDispatcher.lambda$null$14(EventDispatcher.java:340)
[01:35:49 WARN]:        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
[01:35:49 WARN]:        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
[01:35:49 WARN]:        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
[01:35:49 WARN]:        at java.util.concurrent.ConcurrentHashMap$EntrySpliterator.forEachRemaining(Unknown Source)
[01:35:49 WARN]:        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
[01:35:49 WARN]:        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
[01:35:49 WARN]:        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
[01:35:49 WARN]:        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
[01:35:49 WARN]:        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
[01:35:49 WARN]:        at java.util.stream.ReferencePipeline.forEach(Unknown Source)
[01:35:49 WARN]:        at sx.blah.discord.api.events.EventDispatcher.lambda$dispatch$18(EventDispatcher.java:339)
[01:35:49 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[01:35:49 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[01:35:49 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[01:35:49 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[01:35:49 WARN]:        at java.lang.Thread.run(Unknown Source)

**Comment by weeryan17** [comment]
> [01:35:49 WARN]: sx.blah.discord.util.MissingPermissionsException: Missing permissions: MANAGE_ROLES!

Your bot doesn't have the manage roles permission.
