### ISSUE TITLE
Admin on Mc not on Discord 

### ISSUE THREAD

**Issue by ghost** [weeryan17/Discord-Groups#2]
My bot and my server were linked but I'm not in Admin rank on Discord :(

> [18:40:56 INFO]: [PermissionsEx] Enabling PermissionsEx v1.22.7-SNAPSHOT
> [18:40:57 INFO]: [PermissionsEx] Initializing file backend
> [18:40:57 INFO]: [PermissionsEx] Permissions file successfully reloaded
> [18:40:58 INFO]: [Vault][Permission] PermissionsEx hooked.
> [18:40:58 INFO]: [Vault][Chat] PermissionsEx_Chat hooked.
> [18:40:58 INFO]: [DiscordGroups] Enabling DiscordGroups v1.0.0
> [18:41:04 WARN]: Discord4J: ERROR INITIALIZING LOGGER!
> [18:41:04 WARN]: Discord4J: No SLF4J implementation found, reverting to the inte
> rnal implementation (sx.blah.discord.Discord4J$Discord4JLogger)
> [18:41:04 WARN]: Discord4J: It is _highly_ recommended to use an full featured i
> mplementation like logback!
> [18:41:04 WARN]: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder"
> .
> [18:41:04 WARN]: SLF4J: Defaulting to no-operation (NOP) logger implementation
> [18:41:04 WARN]: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder f
> or further details.

[18:41:04 INFO](sx.blah.discord.Discord4J): : [

[18:41:04 INFO](sx.blah.discord.Discord4J): Server thread

[18:41:04 INFO](sx.blah.discord.Discord4J): ] -
[18:41:04 INFO](sx.blah.discord.Discord4J): Discord4J v2.6.0
[18:41:04 INFO](sx.blah.discord.Discord4J):

[18:41:04 INFO](sx.blah.discord.Discord4J): : [

[18:41:04 INFO](sx.blah.discord.Discord4J): Server thread

[18:41:04 INFO](sx.blah.discord.Discord4J): ] -
[18:41:04 INFO](sx.blah.discord.Discord4J): A Java binding for the official Discord API, forked from https:
//github.com/nerd/Discord4J. Copyright (c) 2016, Licensed under GNU GPLv2
[18:41:04 INFO](sx.blah.discord.Discord4J):

[18:41:06 WARN]: [PermissionsEx] The updater could not find any files for the pr
oject id 31279
[18:41:06 WARN]: Could not register alias cdsadd because it contains commands th
at do not exist: region addmember
[18:41:06 INFO](Done): Server permissions file permissions.yml is empty, ignoring it

[18:41:06 INFO](Done): [Vault] Checking for Updates ...
[18:41:07 INFO](sx.blah.discord.Discord4J): [Vault] No new version available

[18:41:07 INFO](sx.blah.discord.Discord4J): : [

[18:41:07 INFO](sx.blah.discord.Discord4J): ] -
[18:41:07 INFO](sx.blah.discord.Discord4J): Connected to the Discord websocket v5
[18:41:07 INFO](sx.blah.discord.Discord4J):

[18:41:07 INFO](sx.blah.discord.Discord4J): : [

[18:41:07 INFO](sx.blah.discord.Discord4J): Request Builder Async Executor

[18:41:07 INFO](sx.blah.discord.Discord4J): ] -
[18:41:07 INFO](sx.blah.discord.Discord4J): Connected to 1 guilds.
[18:41:07 INFO](sx.blah.discord.Discord4J):

[18:41:08 INFO]: [DiscordGroups] bot ready

[18:41:08 WARN](java.lang.NullPointerException): : [

[18:41:08 WARN](java.lang.NullPointerException): Event Dispatch Thread

[18:41:08 WARN](java.lang.NullPointerException): ] -
[18:41:08 WARN](java.lang.NullPointerException): Unhandled exception caught dispatching event ReadyEvent
[18:41:08 WARN](java.lang.NullPointerException):

[18:41:08 WARN](java.lang.NullPointerException):        at com.weeryan17.discord.DiscordEventHandler.onReadyEven
t(DiscordEventHandler.java:36)
[18:41:08 WARN](java.lang.NullPointerException):        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native M
ethod)
[18:41:08 WARN](java.lang.NullPointerException):        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown S
ource)
[18:41:08 WARN](java.lang.NullPointerException):        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unkno
wn Source)
[18:41:08 WARN](java.lang.NullPointerException):        at java.lang.reflect.Method.invoke(Unknown Source)
[18:41:08 WARN](java.lang.NullPointerException):        at sx.blah.discord.api.events.EventDispatcher.lambda$nul
l$8(EventDispatcher.java:282)
[18:41:08 WARN](java.lang.NullPointerException):        at java.util.concurrent.CopyOnWriteArrayList.forEach(Unk
nown Source)
[18:41:08 WARN](java.lang.NullPointerException):        at sx.blah.discord.api.events.EventDispatcher.lambda$nul
l$9(EventDispatcher.java:280)
[18:41:08 WARN](java.lang.NullPointerException):        at java.util.concurrent.ConcurrentHashMap.forEach(Unknow
n Source)
[18:41:08 WARN](java.lang.NullPointerException):        at sx.blah.discord.api.events.EventDispatcher.lambda$nul
l$10(EventDispatcher.java:279)
[18:41:08 WARN](java.lang.NullPointerException):        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Un
known Source)
[18:41:08 WARN](java.lang.NullPointerException):        at java.util.stream.ReferencePipeline$3$1.accept(Unknown
 Source)
[18:41:08 WARN](java.lang.NullPointerException):        at java.util.stream.ReferencePipeline$2$1.accept(Unknown
 Source)
[18:41:08 WARN](java.lang.NullPointerException):        at java.util.concurrent.ConcurrentHashMap$EntrySpliterat
or.forEachRemaining(Unknown Source)
[18:41:08 WARN](java.lang.NullPointerException):        at java.util.stream.AbstractPipeline.copyInto(Unknown So
urce)
[18:41:08 WARN](java.lang.NullPointerException):        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unk
nown Source)
[18:41:08 WARN](java.lang.NullPointerException):        at java.util.stream.ForEachOps$ForEachOp.evaluateSequent
ial(Unknown Source)
[18:41:08 WARN](java.lang.NullPointerException):        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateS
equential(Unknown Source)
[18:41:08 WARN](java.lang.NullPointerException):        at java.util.stream.AbstractPipeline.evaluate(Unknown So
urce)
[18:41:08 WARN](java.lang.NullPointerException):        at java.util.stream.ReferencePipeline.forEach(Unknown So
urce)
[18:41:08 WARN](java.lang.NullPointerException):        at sx.blah.discord.api.events.EventDispatcher.lambda$dis
patch$15(EventDispatcher.java:278)
[18:41:08 WARN](java.lang.NullPointerException):        at java.util.concurrent.Executors$RunnableAdapter.call(U
nknown Source)
[18:41:08 WARN](java.lang.NullPointerException):        at java.util.concurrent.FutureTask.run(Unknown Source)
[18:41:08 WARN](java.lang.NullPointerException):        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unk
nown Source)
[18:41:08 WARN](java.lang.NullPointerException):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Un
known Source)
[18:41:08 WARN](java.lang.NullPointerException):        at java.lang.Thread.run(Unknown Source)

Can you help me?

**Comment by weeryan17** [comment]
I'll look into it. get back to you soon. also just to help me out are you running your server or using a host?

**Comment by ghost** [comment]
My server is runing in localhost

**Comment by ghost** [comment]
(Sorry for my bad english, I'm french)

**Comment by weeryan17** [comment]
"My bot and my server were linked but I'm not in Admin rank on Discord :(" that's because you haven't registered with discord yet. if you look at the discord page it gives you commands for use in discord to link your discord and minecraft users. about the error that you gave me. that error is caused because your main channel in the config is wrong

**Comment by ghost** [comment]
the name of the main channel must containt the # or no?

**Comment by weeryan17** [comment]
no

**Comment by xDiscoZombie** [comment]
In Linked Account :`Players:
  53a5502f-3f95-41f3-9e2a-1a70e01e75f4: '208986158665957376'
Discord Users:
  '208986158665957376': 53a5502f-3f95-41f3-9e2a-1a70e01e75f4`

**Comment by ghost** [comment]
"that error is caused because your main channel in the config is wrong", no, it's true?!

**Comment by weeryan17** [comment]
Yes the error is caused because of an invalid channel name to no was to it needing to contain the #

**Comment by ghost** [comment]
With and without the #, I anyway get error

**Comment by ghost** [comment]
ho :O my bot in discord say "Bot ready to do stuff!" :P

**Comment by ghost** [comment]
But I get a new erreur x)

**Comment by weeryan17** [comment]
about the ranks not working make sure your bot has permission to manage roles

**Comment by ghost** [comment]
New erreur:
'[19:02:31 INFO]: [DiscordGroups] bot ready
[19:02:32 WARN]: sx.blah.discord.util.MissingPermissionsException: Edited roles
hierarchy is too high.
[19:02:32 WARN]:        at sx.blah.discord.api.internal.DiscordUtils.checkPermis
sions(DiscordUtils.java:543)
[19:02:32 WARN]:        at sx.blah.discord.api.internal.DiscordUtils.checkPermis
sions(DiscordUtils.java:621)
[19:02:32 WARN]:        at sx.blah.discord.handle.impl.obj.Role.edit(Role.java:1
87)
[19:02:32 WARN]:        at sx.blah.discord.handle.impl.obj.Role.changeName(Role.
java:219)
[19:02:32 WARN]:        at com.weeryan17.discord.Updater.updateRoles(Updater.jav
a:49)
[19:02:32 WARN]:        at com.weeryan17.discord.DiscordEventHandler.onReadyEven
t(DiscordEventHandler.java:42)
[19:02:32 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native M
ethod)
[19:02:32 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown S
ource)
[19:02:32 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unkno
wn Source)
[19:02:32 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[19:02:32 WARN]:        at sx.blah.discord.api.events.EventDispatcher.lambda$nul
l$8(EventDispatcher.java:282)
[19:02:32 WARN]:        at java.util.concurrent.CopyOnWriteArrayList.forEach(Unk
nown Source)
[19:02:32 WARN]:        at sx.blah.discord.api.events.EventDispatcher.lambda$nul
l$9(EventDispatcher.java:280)
[19:02:32 WARN]:        at java.util.concurrent.ConcurrentHashMap.forEach(Unknow
n Source)
[19:02:32 WARN]:        at sx.blah.discord.api.events.EventDispatcher.lambda$nul
l$10(EventDispatcher.java:279)
[19:02:32 WARN]:        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Un
known Source)
[19:02:32 WARN]:        at java.util.stream.ReferencePipeline$3$1.accept(Unknown
 Source)
[19:02:32 WARN]:        at java.util.stream.ReferencePipeline$2$1.accept(Unknown
 Source)
[19:02:32 WARN]:        at java.util.concurrent.ConcurrentHashMap$EntrySpliterat
or.forEachRemaining(Unknown Source)
[19:02:32 WARN]:        at java.util.stream.AbstractPipeline.copyInto(Unknown So
urce)
[19:02:32 WARN]:        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unk
nown Source)
[19:02:32 WARN]:        at java.util.stream.ForEachOps$ForEachOp.evaluateSequent
ial(Unknown Source)
[19:02:32 WARN]:        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateS
equential(Unknown Source)
[19:02:32 WARN]:        at java.util.stream.AbstractPipeline.evaluate(Unknown So
urce)
[19:02:32 WARN]:        at java.util.stream.ReferencePipeline.forEach(Unknown So
urce)
[19:02:32 WARN]:        at sx.blah.discord.api.events.EventDispatcher.lambda$dis
patch$15(EventDispatcher.java:278)
[19:02:32 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(U
nknown Source)
[19:02:32 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[19:02:32 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unk
nown Source)
[19:02:32 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Un
known Source)
[19:02:32 WARN]:        at java.lang.Thread.run(Unknown Source)
[19:02:32 WARN]: sx.blah.discord.util.MissingPermissionsException: Edited roles
hierarchy is too high.
[19:02:32 WARN]:        at sx.blah.discord.api.internal.DiscordUtils.checkPermis
sions(DiscordUtils.java:543)
[19:02:32 WARN]:        at sx.blah.discord.api.internal.DiscordUtils.checkPermis
sions(DiscordUtils.java:621)
[19:02:32 WARN]:        at sx.blah.discord.handle.impl.obj.Role.edit(Role.java:1
87)
[19:02:32 WARN]:        at sx.blah.discord.handle.impl.obj.Role.changeName(Role.
java:219)
[19:02:32 WARN]:        at com.weeryan17.discord.Updater.updateRoles(Updater.jav
a:49)
[19:02:32 WARN]:        at com.weeryan17.discord.DiscordEventHandler.onReadyEven
t(DiscordEventHandler.java:42)
[19:02:32 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native M
ethod)
[19:02:32 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown S
ource)
[19:02:32 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unkno
wn Source)
[19:02:32 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[19:02:32 WARN]:        at sx.blah.discord.api.events.EventDispatcher.lambda$nul
l$8(EventDispatcher.java:282)
[19:02:32 WARN]:        at java.util.concurrent.CopyOnWriteArrayList.forEach(Unk
nown Source)
[19:02:32 WARN]:        at sx.blah.discord.api.events.EventDispatcher.lambda$nul
l$9(EventDispatcher.java:280)
[19:02:32 WARN]:        at java.util.concurrent.ConcurrentHashMap.forEach(Unknow
n Source)
[19:02:32 WARN]:        at sx.blah.discord.api.events.EventDispatcher.lambda$nul
l$10(EventDispatcher.java:279)
[19:02:32 WARN]:        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Un
known Source)
[19:02:32 WARN]:        at java.util.stream.ReferencePipeline$3$1.accept(Unknown
 Source)
[19:02:32 WARN]:        at java.util.stream.ReferencePipeline$2$1.accept(Unknown
 Source)
[19:02:32 WARN]:        at java.util.concurrent.ConcurrentHashMap$EntrySpliterat
or.forEachRemaining(Unknown Source)
[19:02:32 WARN]:        at java.util.stream.AbstractPipeline.copyInto(Unknown So
urce)
[19:02:32 WARN]:        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unk
nown Source)
[19:02:32 WARN]:        at java.util.stream.ForEachOps$ForEachOp.evaluateSequent
ial(Unknown Source)
[19:02:32 WARN]:        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateS
equential(Unknown Source)
[19:02:32 WARN]:        at java.util.stream.AbstractPipeline.evaluate(Unknown So
urce)
[19:02:32 WARN]:        at java.util.stream.ReferencePipeline.forEach(Unknown So
urce)
[19:02:32 WARN]:        at sx.blah.discord.api.events.EventDispatcher.lambda$dis
patch$15(EventDispatcher.java:278)
[19:02:32 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(U
nknown Source)
[19:02:32 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[19:02:32 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unk
nown Source)
[19:02:32 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Un
known Source)
[19:02:32 WARN]:        at java.lang.Thread.run(Unknown Source)
[19:02:32 WARN]: sx.blah.discord.util.MissingPermissionsException: Edited roles
hierarchy is too high.
[19:02:32 WARN]:        at sx.blah.discord.api.internal.DiscordUtils.checkPermis
sions(DiscordUtils.java:543)
[19:02:32 WARN]:        at sx.blah.discord.api.internal.DiscordUtils.checkPermis
sions(DiscordUtils.java:621)
[19:02:32 WARN]:        at sx.blah.discord.handle.impl.obj.Guild.editUserRoles(G
uild.java:368)
[19:02:32 WARN]:        at com.weeryan17.discord.Updater.updatePlayer(Updater.ja
va:30)
[19:02:32 WARN]:        at com.weeryan17.discord.DiscordEventHandler$1.run(Disco
rdEventHandler.java:47)
[19:02:32 WARN]:        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.r
un(CraftTask.java:71)
[19:02:32 WARN]:        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftSchedu
ler.mainThreadHeartbeat(CraftScheduler.java:350)
[19:02:32 WARN]:        at net.minecraft.server.v1_10_R1.MinecraftServer.D(Minec
raftServer.java:741)
[19:02:32 WARN]:        at net.minecraft.server.v1_10_R1.DedicatedServer.D(Dedic
atedServer.java:399)
[19:02:32 WARN]:        at net.minecraft.server.v1_10_R1.MinecraftServer.C(Minec
raftServer.java:672)
[19:02:32 WARN]:        at net.minecraft.server.v1_10_R1.MinecraftServer.run(Min
ecraftServer.java:571)
[19:02:32 WARN]:        at java.lang.Thread.run(Unknown Source)
[19:03:22 WARN]: sx.blah.discord.util.MissingPermissionsException: Edited roles
hierarchy is too high.
[19:03:22 WARN]:        at sx.blah.discord.api.internal.DiscordUtils.checkPermis
sions(DiscordUtils.java:543)
[19:03:22 WARN]:        at sx.blah.discord.api.internal.DiscordUtils.checkPermis
sions(DiscordUtils.java:621)
[19:03:22 WARN]:        at sx.blah.discord.handle.impl.obj.Guild.editUserRoles(G
uild.java:368)
[19:03:22 WARN]:        at com.weeryan17.discord.Updater.updatePlayer(Updater.ja
va:30)
[19:03:22 WARN]:        at com.weeryan17.discord.DiscordEventHandler$1.run(Disco
rdEventHandler.java:47)
[19:03:22 WARN]:        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.r
un(CraftTask.java:71)
[19:03:22 WARN]:        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftSchedu
ler.mainThreadHeartbeat(CraftScheduler.java:350)
[19:03:22 WARN]:        at net.minecraft.server.v1_10_R1.MinecraftServer.D(Minec
raftServer.java:741)
[19:03:22 WARN]:        at net.minecraft.server.v1_10_R1.DedicatedServer.D(Dedic
atedServer.java:399)
[19:03:22 WARN]:        at net.minecraft.server.v1_10_R1.MinecraftServer.C(Minec
raftServer.java:672)
[19:03:22 WARN]:        at net.minecraft.server.v1_10_R1.MinecraftServer.run(Min
ecraftServer.java:571)
[19:03:22 WARN]:        at java.lang.Thread.run(Unknown Source)
[19:04:13 WARN]: sx.blah.discord.util.MissingPermissionsException: Edited roles
hierarchy is too high.
[19:04:13 WARN]:        at sx.blah.discord.api.internal.DiscordUtils.checkPermis
sions(DiscordUtils.java:543)
[19:04:13 WARN]:        at sx.blah.discord.api.internal.DiscordUtils.checkPermis
sions(DiscordUtils.java:621)
[19:04:13 WARN]:        at sx.blah.discord.handle.impl.obj.Guild.editUserRoles(G
uild.java:368)
[19:04:13 WARN]:        at com.weeryan17.discord.Updater.updatePlayer(Updater.ja
va:30)
[19:04:13 WARN]:        at com.weeryan17.discord.DiscordEventHandler$1.run(Disco
rdEventHandler.java:47)
[19:04:13 WARN]:        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.r
un(CraftTask.java:71)
[19:04:13 WARN]:        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftSchedu
ler.mainThreadHeartbeat(CraftScheduler.java:350)
[19:04:13 WARN]:        at net.minecraft.server.v1_10_R1.MinecraftServer.D(Minec
raftServer.java:741)
[19:04:13 WARN]:        at net.minecraft.server.v1_10_R1.DedicatedServer.D(Dedic
atedServer.java:399)
[19:04:13 WARN]:        at net.minecraft.server.v1_10_R1.MinecraftServer.C(Minec
raftServer.java:672)
[19:04:13 WARN]:        at net.minecraft.server.v1_10_R1.MinecraftServer.run(Min
ecraftServer.java:571)
[19:04:13 WARN]:        at java.lang.Thread.run(Unknown Source)'

My bot had all permissions

**Comment by weeryan17** [comment]
Yeah it's an error with permissions. You have a role higher then the bot and it's having difficulty with that role

**Comment by ghost** [comment]
I'm the creator of the discord server, it can come from ?

**Comment by weeryan17** [comment]
Don't know what you asking their sorry :(. Anyways try taking away your current role on the server and try that

**Comment by ghost** [comment]
I do not have rool on discord, I'm just creator

**Comment by weeryan17** [comment]
Well i don't know then. it's not an issue i can fix my side anyways.

**Comment by weeryan17** [comment]
@xDiscoZombie so after looking this up some more make sure your bots role that your bot uses is at the top
